import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1756140971147 implements MigrationInterface {
    name = 'InitialSchema1756140971147'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."tenants_plan_enum" AS ENUM('standard', 'pro', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_isolationmode_enum" AS ENUM('rls', 'schema')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "subdomain" character varying NOT NULL, "apiKey" character varying, "plan" "public"."tenants_plan_enum" NOT NULL DEFAULT 'standard', "isolationMode" "public"."tenants_isolationmode_enum" NOT NULL DEFAULT 'rls', "schemaName" character varying, "isActive" boolean NOT NULL DEFAULT true, "logoUrl" character varying, "primaryColor" character varying, "secondaryColor" character varying, "contactEmail" character varying, "contactPhone" character varying, "settings" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"), CONSTRAINT "UQ_21bb89e012fa5b58532009c1601" UNIQUE ("subdomain"), CONSTRAINT "UQ_30dec5cd2d1f58a2682a9c77bb8" UNIQUE ("apiKey"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32731f181236a46182a38c992a" ON "tenants" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_21bb89e012fa5b58532009c160" ON "tenants" ("subdomain") `);
        await queryRunner.query(`CREATE INDEX "IDX_30dec5cd2d1f58a2682a9c77bb" ON "tenants" ("apiKey") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('super_admin', 'admin', 'teacher', 'parent')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "refreshTokenHash" character varying, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phone" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'teacher', "isActive" boolean NOT NULL DEFAULT true, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_plan_enum" AS ENUM('standard', 'pro', 'enterprise')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'cancelled', 'expired', 'pending')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billingcycle_enum" AS ENUM('monthly', 'quarterly', 'yearly')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan" "public"."subscriptions_plan_enum" NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'pending', "billingCycle" "public"."subscriptions_billingcycle_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "discount" numeric(10,2), "startDate" date NOT NULL, "endDate" date NOT NULL, "trialEndDate" date, "paymentReference" character varying, "metadata" jsonb, "tenantId" uuid NOT NULL, "providerSubscriptionId" character varying, "nextBillingDate" TIMESTAMP, "cancelledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schools_level_enum" AS ENUM('primary', 'o_level', 'a_level', 'combined')`);
        await queryRunner.query(`CREATE TABLE "schools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying, "level" "public"."schools_level_enum" NOT NULL DEFAULT 'primary', "address" character varying, "city" character varying, "district" character varying, "region" character varying, "postalCode" character varying, "phone" character varying, "email" character varying, "website" character varying, "logoUrl" character varying, "settings" jsonb, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95b932e47ac129dd8e23a0db548" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32fbaf4feccea51ef7aeefa62b" ON "schools" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."students_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."students_status_enum" AS ENUM('active', 'inactive', 'graduated', 'transferred', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lin" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "middleName" character varying, "gender" "public"."students_gender_enum", "dateOfBirth" date, "placeOfBirth" character varying, "address" character varying, "phone" character varying, "email" character varying, "parentName" character varying, "parentPhone" character varying, "parentEmail" character varying, "class" character varying, "stream" character varying, "status" "public"."students_status_enum" NOT NULL DEFAULT 'active', "admissionDate" date, "graduationDate" date, "photoUrl" character varying, "medicalInfo" jsonb, "additionalInfo" jsonb, "tenantId" uuid NOT NULL, "schoolId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b4986851238d6559015d0cd69e3" UNIQUE ("lin"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4986851238d6559015d0cd69e" ON "students" ("lin") `);
        await queryRunner.query(`CREATE TYPE "public"."assessments_type_enum" AS ENUM('exam', 'test', 'quiz', 'assignment', 'project', 'practical')`);
        await queryRunner.query(`CREATE TYPE "public"."assessments_examlevel_enum" AS ENUM('ple', 'uce', 'uace')`);
        await queryRunner.query(`CREATE TYPE "public"."assessments_grade_enum" AS ENUM('D1', 'D2', 'C3', 'C4', 'C5', 'C6', 'P7', 'P8', 'F9', 'A', 'B', 'C', 'D', 'E', 'O', 'F')`);
        await queryRunner.query(`CREATE TABLE "assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."assessments_type_enum" NOT NULL, "examLevel" "public"."assessments_examlevel_enum" NOT NULL, "caScore" numeric(5,2), "examScore" numeric(5,2), "totalScore" numeric(5,2), "grade" "public"."assessments_grade_enum", "points" integer, "remark" character varying, "metadata" jsonb, "tenantId" uuid NOT NULL, "studentId" uuid NOT NULL, "subjectId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3442bd80a00e9111cefca57f6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c594c233d1ab51a91894162e5e" ON "assessments" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."subjects_type_enum" AS ENUM('core', 'elective', 'optional')`);
        await queryRunner.query(`CREATE TYPE "public"."subjects_examlevel_enum" AS ENUM('ple', 'uce', 'uace')`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "description" character varying, "type" "public"."subjects_type_enum" NOT NULL DEFAULT 'core', "examLevel" "public"."subjects_examlevel_enum" NOT NULL, "isCompulsory" boolean NOT NULL DEFAULT false, "gradingCriteria" jsonb, "tenantId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_542cbba74dde3c82ab49c573109" UNIQUE ("code"), CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_47a287fe64bd0e1027e603c335" ON "subjects" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_542cbba74dde3c82ab49c57310" ON "subjects" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_provider_enum" AS ENUM('paystack', 'mobile_money', 'bank_transfer')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'processing', 'successful', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_type_enum" AS ENUM('subscription', 'invoice', 'one_time')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "provider" "public"."payments_provider_enum" NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "type" "public"."payments_type_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "fee" numeric(10,2), "metadata" jsonb, "tenantId" uuid NOT NULL, "subscriptionId" uuid, "paidAt" TIMESTAMP, "refundedAt" TIMESTAMP, "providerPaymentId" character varying, "providerResponse" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_866ddee0e17d9385b4e3b86851" ON "payments" ("reference") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('email', 'sms', 'push', 'in_app')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'delivered', 'failed', 'read')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_category_enum" AS ENUM('report_ready', 'payment_received', 'subscription_renewal', 'account_activation', 'password_reset', 'system_alert')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "content" character varying NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "category" "public"."notifications_category_enum" NOT NULL, "recipient" character varying, "metadata" jsonb, "tenantId" uuid NOT NULL, "userId" uuid, "sentAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "readAt" TIMESTAMP, "providerResponse" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_762a36a52d3233955639e53dec" ON "notifications" ("title") `);
        await queryRunner.query(`CREATE TYPE "public"."import_jobs_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "import_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fileName" character varying NOT NULL, "fileSize" integer NOT NULL, "type" character varying NOT NULL, "status" "public"."import_jobs_status_enum" NOT NULL DEFAULT 'pending', "result" jsonb, "errorMessage" character varying, "downloadUrl" character varying, "tenantId" uuid NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "completedAt" TIMESTAMP, CONSTRAINT "PK_4d206c602f173f98e4bb85819a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c562ea5f9a1e52a5d2de39fef" ON "import_jobs" ("fileName") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'read', 'update', 'delete', 'login', 'logout', 'export', 'import', 'payment', 'subscription')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."audit_logs_action_enum" NOT NULL, "entity" character varying NOT NULL, "entityId" character varying, "oldValues" jsonb, "newValues" jsonb, "metadata" jsonb, "tenantId" uuid NOT NULL, "userId" uuid, "userAgent" character varying, "ipAddress" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_c58f7e88c286e5e3478960a998b" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_0c5fe8e5f9f4dd4a8c0134abc9c" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schools" ADD CONSTRAINT "FK_f539bc33c6398e983cda7bda256" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_0fe5a6912f421e1c20615814426" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_44855579fce3690c57ae8b12999" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_f918a577186968cf65f4645fbe8" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_0bedc1cc7c7242bf78246fbf4bd" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_3d790fa48896e741af9462721cd" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_f382f7fa7a7084e487981938b53" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_98a04cdcbac4f6a2c55c7d19350" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_d5b86bc522af7cc9e3e13960ffb" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ADD CONSTRAINT "FK_0fbdddbdd6c2f77f712cd887745" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_889633a4291bcb0bf4680fff234" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_889633a4291bcb0bf4680fff234"`);
        await queryRunner.query(`ALTER TABLE "import_jobs" DROP CONSTRAINT "FK_0fbdddbdd6c2f77f712cd887745"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_d5b86bc522af7cc9e3e13960ffb"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_98a04cdcbac4f6a2c55c7d19350"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_f382f7fa7a7084e487981938b53"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_3d790fa48896e741af9462721cd"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_0bedc1cc7c7242bf78246fbf4bd"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_f918a577186968cf65f4645fbe8"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_44855579fce3690c57ae8b12999"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_0fe5a6912f421e1c20615814426"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP CONSTRAINT "FK_f539bc33c6398e983cda7bda256"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_0c5fe8e5f9f4dd4a8c0134abc9c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_c58f7e88c286e5e3478960a998b"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c562ea5f9a1e52a5d2de39fef"`);
        await queryRunner.query(`DROP TABLE "import_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."import_jobs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_762a36a52d3233955639e53dec"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866ddee0e17d9385b4e3b86851"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_542cbba74dde3c82ab49c57310"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47a287fe64bd0e1027e603c335"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP TYPE "public"."subjects_examlevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subjects_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c594c233d1ab51a91894162e5e"`);
        await queryRunner.query(`DROP TABLE "assessments"`);
        await queryRunner.query(`DROP TYPE "public"."assessments_grade_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assessments_examlevel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."assessments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4986851238d6559015d0cd69e"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."students_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32fbaf4feccea51ef7aeefa62b"`);
        await queryRunner.query(`DROP TABLE "schools"`);
        await queryRunner.query(`DROP TYPE "public"."schools_level_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billingcycle_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_plan_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30dec5cd2d1f58a2682a9c77bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21bb89e012fa5b58532009c160"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32731f181236a46182a38c992a"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_isolationmode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_plan_enum"`);
    }

}
